# fly.toml app configuration file generated for ar-io-node-proxy on 2023-09-14T16:17:12Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ar-io-node-proxy"
primary_region = "ams"

[build]
  image = "ghcr.io/ar-io/ar-io-envoy:c6c48f53a8f60ccfd007fdd3dbc2ed481340e25d"

[env]
  TVAL_AR_IO_HOST = "ar-io-node.flycast"
  TVAL_AR_IO_PORT = "80" # Fly.io maps http_service to 80 by default
  TVAL_GATEWAY_HOST = "arweave.dev"
  TVAL_GRAPHQL_HOST = "ar-io-node.flycast"
  TVAL_GRAPHQL_PORT = "80" # Fly.io maps http_service to 80 by default
  TVAL_ARNS_ROOT_HOST= "arweave.fllstck.dev"
  TVAL_OBSERVER_HOST= "ar-io-observer.flycast"
  TVAL_OBSERVER_PORT = "80" # Fly.io maps http_service to 80 by default

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[http_service.concurrency]
  hard_limit = 1024
  soft_limit = 1000
  type = "connections"