# fly.toml app configuration file generated for ar-io-observer on 2023-10-24T20:26:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# This service will be available via ar-io-observer.flycast
app = "ar-io-observer"
primary_region = "ams"

[build]
  image = "ghcr.io/ar-io/ar-io-observer:6449bcb6dda778fef68a94bd29343190524439db"

[env]
  PORT = "5000"
  RUN_OBSERVER = "true"
  SUBMIT_CONTRACT_INTERACTIONS = "true"
  NUM_ARNS_NAMES_TO_OBSERVE_PER_GROUP = "5"
# OBSERVER_WALLET=***
# CONTRACT_ID=default

[http_service]
  internal_port = 5000
  force_https = false # Only accessed via proxy (private IPv6), doesn't need SSL
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
