# fly.toml app configuration file generated for ar-io-observer on 2023-10-24T20:26:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# This service will be available via ar-io-observer.flycast
app = "ar-io-observer"
primary_region = "ams"

[build]
  image = "ghcr.io/ar-io/ar-io-observer:c6af93b8f2213180b630009fab8b435afaf47395"

[env]
  LOG_LEVEL = "info"
  PORT = "5050"
  RUN_OBSERVER = "true"
  SUBMIT_CONTRACT_INTERACTIONS = "true"
  NUM_ARNS_NAMES_TO_OBSERVE_PER_GROUP = "8"
  MIN_RELEASE_NUMBER="0"
  AR_IO_NODE_RELEASE="27"
  OBSERVER_WALLET="lk2W8J5mj9JDpl22p1WMC05gD7EqWJZbbAgOAswC9xk"
# OBSERVER_JWK=***
# CONTRACT_ID=default

[http_service]
  internal_port = 5050
  force_https = false # Only accessed via proxy (private IPv6), doesn't need SSL
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
