name: Deploy Observer
on:
  push:
    branches:
      - fly-deployment
    paths:
      - 'observer/**'
jobs:
  deploy:
    name: Deploy Observer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: ./observer
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
